export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';

export const ADD_SALARY = 'ADD_SALARY';
export const SALARY_LOADING = 'SALARY_LOADING';
export const SALARY_FAILED = 'SALARY_FAILED';

export const ADD_STAFF_DEPARTMENTS = 'ADD_STAFF_DEPARTMENTS';
export const STAFF_DEPARTMENTS_LOADING = 'STAFF_DEPARTMENTS_LOADING';
export const STAFF_DEPARTMENTS_FAILED = 'STAFF_DEPARTMENTS_FAILED';

export const ADD_NEWSTAFFS = 'ADD_NEWSTAFFS';
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';